/**
 * OAuth server provider for @voiden/mcp's --oauth mode.
 *
 * This is deliberately NOT a real identity check. voiden-mcp is a
 * single-operator, locally-run tool: whoever can reach the listening
 * URL (a loopback bind, or a hard-to-guess --tunnel URL) already has full,
 * unauthenticated tool-call access today — that's the actual trust boundary,
 * and OAuth doesn't change it. This provider exists purely so OAuth-strict
 * MCP clients (claude.ai connectors, CLI agents doing an RFC 8252
 * loopback-redirect flow) can complete the handshake they require.
 * Accordingly, `authorize()` auto-approves — no click-to-consent gate, no
 * login — matching the MCP SDK's own reference/demo provider. It still
 * renders a small landing page (rather than a bare invisible redirect) so a
 * human watching a browser-driven flow sees confirmation of what's
 * happening; see renderAutoApprovePage() below for why that's a 200+HTML
 * page rather than a real 302 (a redirect status would make the browser
 * skip past it before it could ever render).
 */

import { randomBytes } from 'crypto'
import type { Response } from 'express'
import type {
  OAuthServerProvider,
  AuthorizationParams,
} from '@modelcontextprotocol/sdk/server/auth/provider.js'
import type { OAuthRegisteredClientsStore } from '@modelcontextprotocol/sdk/server/auth/clients.js'
import type { AuthInfo } from '@modelcontextprotocol/sdk/server/auth/types.js'
import {
  InvalidGrantError,
  InvalidTokenError,
} from '@modelcontextprotocol/sdk/server/auth/errors.js'
import type {
  OAuthClientInformationFull,
  OAuthTokenRevocationRequest,
  OAuthTokens,
} from '@modelcontextprotocol/sdk/shared/auth.js'
import {
  getStoredClient,
  putStoredClient,
  getToken,
  deleteToken,
  getRefreshToken,
  deleteRefreshToken,
  issueTokenPair,
} from './oauthStore.js'

const ACCESS_TOKEN_TTL_SECONDS = 60 * 60 // 1h — refresh tokens don't expire until revoked
const AUTH_CODE_TTL_MS = 10 * 60 * 1000 // 10min — plenty for a browser round-trip

interface PendingCode {
  clientId: string
  codeChallenge: string
  redirectUri: string
  scopes: string[]
  resource?: string
  expiresAt: number
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
}

/**
 * A 200 response with an HTML body, not a 302 — a real redirect status would
 * make a browser follow it immediately without ever rendering the body, so
 * there'd be nothing to see. The meta-refresh + inline script both navigate
 * to the same URL; the visible link is the fallback if both are blocked.
 */
function renderAutoApprovePage(clientName: string, redirectUrl: string): string {
  const safeName = escapeHtml(clientName)
  const safeUrlAttr = escapeHtml(redirectUrl)
  const safeUrlJs = JSON.stringify(redirectUrl)
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Voiden MCP</title>
<meta http-equiv="refresh" content="0;url=${safeUrlAttr}">
<style>
  body { font: 15px -apple-system, system-ui, sans-serif; background: #0b0b0c; color: #e4e4e7; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; }
  .card { text-align: center; }
  .check { font-size: 32px; }
  a { color: #8ab4f8; }
</style>
</head>
<body>
  <div class="card">
    <div class="check">✓</div>
    <p>Voiden MCP — authorizing <strong>${safeName}</strong>…</p>
    <p><a id="continue-link" href="${safeUrlAttr}">Continue</a></p>
  </div>
  <script>location.replace(${safeUrlJs})</script>
</body>
</html>`
}

class FileBackedClientsStore implements OAuthRegisteredClientsStore {
  getClient(clientId: string): OAuthClientInformationFull | undefined {
    return getStoredClient(clientId)
  }

  // Client ID/secret generation happens in the SDK's own
  // clientRegistrationHandler before this is called — we just persist and
  // hand back what we were given (see OAuthRegisteredClientsStore's own doc
  // comment: "The client ID and secret will be automatically generated by
  // the library").
  registerClient(
    client: Omit<OAuthClientInformationFull, 'client_id' | 'client_id_issued_at'> & Partial<Pick<OAuthClientInformationFull, 'client_id' | 'client_id_issued_at'>>,
  ): OAuthClientInformationFull {
    const full = client as OAuthClientInformationFull
    putStoredClient(full)
    return full
  }
}

export class VoidenOAuthProvider implements OAuthServerProvider {
  readonly clientsStore: OAuthRegisteredClientsStore = new FileBackedClientsStore()

  private readonly pendingCodes = new Map<string, PendingCode>()

  async authorize(client: OAuthClientInformationFull, params: AuthorizationParams, res: Response): Promise<void> {
    const code = randomBytes(32).toString('base64url')
    this.pendingCodes.set(code, {
      clientId: client.client_id,
      codeChallenge: params.codeChallenge,
      redirectUri: params.redirectUri,
      scopes: params.scopes ?? [],
      resource: params.resource?.toString(),
      expiresAt: Date.now() + AUTH_CODE_TTL_MS,
    })

    const redirectUrl = new URL(params.redirectUri)
    redirectUrl.searchParams.set('code', code)
    if (params.state !== undefined) redirectUrl.searchParams.set('state', params.state)

    res.status(200).type('html').send(renderAutoApprovePage(client.client_name ?? client.client_id, redirectUrl.toString()))
  }

  private takePendingCode(client: OAuthClientInformationFull, authorizationCode: string, { deleteIt }: { deleteIt: boolean }): PendingCode {
    const pending = this.pendingCodes.get(authorizationCode)
    if (!pending || pending.clientId !== client.client_id || pending.expiresAt < Date.now()) {
      this.pendingCodes.delete(authorizationCode)
      throw new InvalidGrantError('Authorization code is invalid, expired, or was issued to a different client')
    }
    if (deleteIt) this.pendingCodes.delete(authorizationCode)
    return pending
  }

  async challengeForAuthorizationCode(client: OAuthClientInformationFull, authorizationCode: string): Promise<string> {
    return this.takePendingCode(client, authorizationCode, { deleteIt: false }).codeChallenge
  }

  async exchangeAuthorizationCode(
    client: OAuthClientInformationFull,
    authorizationCode: string,
    _codeVerifier?: string,
    redirectUri?: string,
    _resource?: URL,
  ): Promise<OAuthTokens> {
    // PKCE (code_verifier vs. the codeChallenge from challengeForAuthorizationCode)
    // is already verified by the SDK's token handler before this is called —
    // single-use consumption happens here, after that check has passed.
    const pending = this.takePendingCode(client, authorizationCode, { deleteIt: true })
    if (redirectUri && redirectUri !== pending.redirectUri) {
      throw new InvalidGrantError('redirect_uri does not match the one used to start this authorization')
    }

    const { accessToken, refreshToken, expiresAt } = issueTokenPair(client.client_id, pending.scopes, pending.resource, ACCESS_TOKEN_TTL_SECONDS)
    return {
      access_token: accessToken,
      token_type: 'Bearer',
      expires_in: expiresAt - Math.floor(Date.now() / 1000),
      refresh_token: refreshToken,
      scope: pending.scopes.join(' ') || undefined,
    }
  }

  async exchangeRefreshToken(
    client: OAuthClientInformationFull,
    refreshToken: string,
    scopes?: string[],
    resource?: URL,
  ): Promise<OAuthTokens> {
    const stored = getRefreshToken(refreshToken)
    if (!stored || stored.clientId !== client.client_id) {
      throw new InvalidGrantError('Refresh token is invalid or was issued to a different client')
    }
    // Rotate: the old refresh token is consumed, a new pair is issued —
    // standard practice, and matches this store's single-entry-per-token shape.
    deleteRefreshToken(refreshToken)
    const effectiveScopes = scopes ?? stored.scopes
    const effectiveResource = resource?.toString() ?? stored.resource
    const { accessToken, refreshToken: newRefreshToken, expiresAt } = issueTokenPair(
      client.client_id, effectiveScopes, effectiveResource, ACCESS_TOKEN_TTL_SECONDS,
    )
    return {
      access_token: accessToken,
      token_type: 'Bearer',
      expires_in: expiresAt - Math.floor(Date.now() / 1000),
      refresh_token: newRefreshToken,
      scope: effectiveScopes.join(' ') || undefined,
    }
  }

  async verifyAccessToken(token: string): Promise<AuthInfo> {
    const stored = getToken(token)
    if (!stored) throw new InvalidTokenError('Access token not recognized')
    if (stored.expiresAt < Math.floor(Date.now() / 1000)) {
      deleteToken(token)
      throw new InvalidTokenError('Access token expired')
    }
    return {
      token,
      clientId: stored.clientId,
      scopes: stored.scopes,
      expiresAt: stored.expiresAt,
      resource: stored.resource ? new URL(stored.resource) : undefined,
    }
  }

  async revokeToken(_client: OAuthClientInformationFull, request: OAuthTokenRevocationRequest): Promise<void> {
    // "If the given token is invalid or already revoked, this method should
    // do nothing" — the hint isn't always reliable, so just try both.
    deleteToken(request.token)
    deleteRefreshToken(request.token)
  }
}
