name: voiden
title: Voiden
summary: API development tool
description: |
  Build, Test, Document & Collaborate.
  Streamline your API development process with Voiden.
license: Apache-2.0
contact: info@voiden.md
website: https://voiden.md
issues: https://github.com/VoidenHQ/voiden/issues

base: core22
confinement: classic
grade: stable

architectures:
  - build-on: amd64

apps:
  voiden:
    command: usr/lib/voiden/voiden
    desktop: usr/share/applications/voiden.desktop
    environment:
      DISABLE_GPU_SANDBOX: "1"

parts:
  voiden-deb:
    plugin: dump
    source: ../out/make/deb/x64/*.deb
    source-type: deb
    stage-packages:
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libxss1
      - libxtst6
      - xdg-utils
      - libatspi2.0-0
      - libuuid1
      - libsecret-1-0
